USE roundrobin_db;

INSERT INTO eventAssociations (trackingNumber, packageRecd, eventId, userId, matchedUserId)
VALUES ("", false, 1, 1, NULL),
				("", false, 1, 2, NULL),
				("", false, 1, 3, NULL),
				("", false, 1, 4, NULL),
				("", false, 1, 5, NULL),
				("", false, 1, 6, NULL),
				("", false, 1, 7, NULL),
				("", false, 1, 8, NULL),
				("", false, 1, 9, NULL),			
				("", false, 1, 10, NULL),
				("", false, 2, 2, NULL),
				("", false, 2, 11, NULL),
				("", false, 2, 12, NULL),
				("", false, 2, 13, NULL),
				("", false, 2, 14, NULL),
				("", false, 2, 15, NULL),
				("", false, 3, 16, NULL),
				("", false, 3, 17, NULL),
				("", false, 3, 18, NULL),
				("", false, 3, 19, NULL),
				("", false, 3, 20, NULL),
				("", false, 3, 3, NULL),
				("", false, 4, 4, NULL),
				("", false, 4, 1, NULL),
				("", false, 4, 2, NULL),
				("", false, 4, 3, NULL),
				("", false, 4, 5, NULL),
				("", false, 4, 6, NULL),
				("", false, 4, 7, NULL),
				("", false, 4, 8, NULL),
				("", false, 4, 9, NULL),
				("", false, 5, 5, 1),
				("", false, 5, 1, 5),
				("", false, 2, 1, NULL);